name: Check AWS

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'aws/**'
      - 'register-batch/aws/**'
  workflow_dispatch:

jobs:
  check-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate GitHub Actions IAM
        run: |
          aws cloudformation validate-template \
            --template-body file://aws/github-actions-iam.yaml

      - name: Validate Register Batch ECR
        run: |
          aws cloudformation validate-template \
            --template-body file://register-batch/aws/ecr.yaml

      - name: Validate Dev Register Batch ECR
        run: |
          aws cloudformation validate-template \
            --template-body file://register-batch/aws/dev-ecr.yaml

      - name: Validate Register Batch Security Group
        run: |
          aws cloudformation validate-template \
            --template-body file://register-batch/aws/sg.yaml

      - name: Validate Dev Register Batch Security Group
        run: |
          aws cloudformation validate-template \
            --template-body file://register-batch/aws/dev-sg.yaml

      - name: Validate Register Batch
        run: |
          aws cloudformation validate-template \
            --template-body file://register-batch/aws/batch.yaml

      - name: Validate Dev Register Batch
        run: |
          aws cloudformation validate-template \
            --template-body file://register-batch/aws/dev-batch.yaml
